Repository rancher/hosted-providers-e2e, pull requests merged in 2024-10, with the labels that each got.

#176 Update GCP template mainly for updated azure-cli package
  .github/workflows/aks.yaml
  .github/workflows/eks.yaml
  .github/workflows/gke.yaml
Labels: enhancement

#177 Set expiration time for GCP runner secrets
  .github/workflows/main.yaml
Labels: bug

#178 Don't use SSH for AKS nodes
  hosted/aks/helper/helper_cluster.go
Labels: bug

#181 Add weekly schedule run for P1 tests
  .github/workflows/aks.yaml
  .github/workflows/eks.yaml
  .github/workflows/gke.yaml
Labels: enhancement, github_actions

#182 Fix az janitor query
  .github/workflows/janitor.yaml
Labels: bug

#184 Run Sync and EKS tests in parallel nodes and Bump k8s version
  .github/workflows/aks.yaml
  .github/workflows/eks.yaml
  .github/workflows/gke.yaml
  Makefile
Labels: enhancement

#187 Added GKE Regional cluster tests
  hosted/gke/helper/helper_cluster.go
  hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
  hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go
  hosted/gke/p0/p0_import_test.go
  hosted/gke/p0/p0_provisioning_test.go
  hosted/gke/p0/p0_suite_test.go
  hosted/gke/p1/p1_import_test.go
  hosted/gke/p1/p1_provisioning_test.go
  hosted/gke/p1/p1_suite_test.go
  hosted/gke/p1/sync_provisioning_test.go
  hosted/gke/support_matrix/support_matrix_provisioning_test.go
  hosted/helpers/helper_common.go
Labels: enhancement

#188 Update aws-janitor repo
  .github/workflows/janitor.yaml
Labels: bug

#193 Run P1Prov in parallel nodes
  Makefile
  hosted/aks/p1/p1_provisioning_test.go
  hosted/aks/p1/p1_suite_test.go
Labels: enhancement
